/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bms;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sandeep
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Backlogs data to Excel File ");
        setResizable(false);

        jButton1.setText("EEE Backlogs Data To Excel File ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CSE Backlogs Data To Excel File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ECE Backlogs Data To Excel File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("GO BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        ResultSet rs = null;
        Statement smt = null;
        ArrayList data = new ArrayList();
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite3\\bms");
            con.setAutoCommit(false);
            System.out.println("Opened database successfully");
            smt = con.createStatement();
            rs = smt.executeQuery("Select * from eee");
           
            String hno = "Hallticket Number";
            String name = "Student Name";
            String s1 = "Semester1";
            String s2 = "Semester2";
            String s3 = "Semester3";
            String s4 = "Semester4";
            String s5 = "Semester5";
            String s6 = "Semester6";
            String s7 = "Semester7";
            String s8 = "Semester8";

            data.add("                     Priyadarshini Engineering College Khammam EEE Backlogs Details  ");
            data.add(hno + "," + name + "," + s1 + "," + s2 + "," + s3 + "," + s4 + "," + s5 + "," + s6 + "," + s7 + "," + s8);
            while (rs.next()) {
                String dhno = rs.getString(1);
                String dname = rs.getString(2);
                String ds1 = rs.getString(3);
                ds1=ds1.replaceAll(",","-");
                
                String ds2 = rs.getString(4);
                if(ds2 != null)
                {
                ds2=ds2.replaceAll(",", "-");
                }
                
                String ds3 = rs.getString(5);
                if(ds3 != null)
                {
                ds3=ds3.replaceAll(",", "-");
                }
                
                String ds4 = rs.getString(6);
                if(ds4 != null)
                {
                ds4=ds4.replaceAll(",", "-");
                }
                
                String ds5 = rs.getString(7);
                if(ds5 != null)
                {
                ds5=ds5.replaceAll(",", "-");
                }
                
                String ds6 = rs.getString(8);
                if(ds6 != null)
                {
                ds6=ds6.replaceAll(",", "-");
                }
                
                String ds7 = rs.getString(9);
                if(ds7 != null)
                {
                ds7=ds7.replaceAll(",", "-");
                }
                
                String ds8 = rs.getString(10);
                if(ds2 != null)
                {
                ds8=ds8.replaceAll(",", "-");
                }
                
                if (ds1 == null) {
                    ds1 = " ";
                }
                if (ds2 == null) {
                    ds2 = " ";
                }
                if (ds3 == null) {
                    ds3 = " ";
                }
                if (ds4 == null) {
                    ds4 = " ";
                }
                if (ds5 == null) {
                    ds5 = " ";
                }
                if (ds6 == null) {
                    ds6 = " ";
                }
                if (ds7 == null) {
                    ds7 = " ";
                }
                if (ds8 == null) {
                    ds8 = " ";
                }
                data.add(dhno + "," + dname + "," + ds1 + "," + ds2 + "," + ds3 + "," + ds4 + "," + ds5 + "," + ds6 + "," + ds7 + "," + ds8);
            }
            // System.out.println(data);
            JOptionPane.showMessageDialog(null, "Done writing", "infromation", JOptionPane.INFORMATION_MESSAGE);
            Iterator i = data.listIterator();
            FileOutputStream fis = new FileOutputStream("eeebacklogs.csv");
            try (PrintWriter pw = new PrintWriter(fis)) {
                pw.append("\n");
                while (i.hasNext()) {
                    pw.append((CharSequence) i.next());
                    pw.append("\n");
                }
                pw.close();
                JOptionPane.showMessageDialog(null, "Done completed", "infromation", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (FileNotFoundException ex) {
             JOptionPane.showMessageDialog(null, "Cannot Open File ", "File in Use", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | SQLException e) {
             JOptionPane.showMessageDialog(null, "Problem With Database", "Infromation", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        ResultSet rs = null;
        Statement smt = null;
        ArrayList data = new ArrayList();
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite3\\bms");
            con.setAutoCommit(false);
            System.out.println("Opened database successfully");
            smt = con.createStatement();
            rs = smt.executeQuery("Select * from cse");
            ResultSetMetaData rsmd = rs.getMetaData();
            String hno = "Hallticket Number";
            String name = "Student Name";
            String s1 = "Semester1";
            String s2 = "Semester2";
            String s3 = "Semester3";
            String s4 = "Semester4";
            String s5 = "Semester5";
            String s6 = "Semester6";
            String s7 = "Semester7";
            String s8 = "Semester8";
            data.add("                   Priyadarshini Engineering College Khammam EEE Backlogs Details");
            data.add(hno + "," + name + "," + s1 + "," + s2 + "," + s3 + "," + s4 + "," + s5 + "," + s6 + "," + s7 + "," + s8);
            while (rs.next()) {
                String dhno = rs.getString(1);
                String dname = rs.getString(2);
                String ds1 = rs.getString(3);
                ds1=ds1.replaceAll(",","-");
                
                String ds2 = rs.getString(4);
                if(ds2 != null)
                {
                ds2=ds2.replaceAll(",", "-");
                }
                
                String ds3 = rs.getString(5);
                if(ds3 != null)
                {
                ds3=ds3.replaceAll(",", "-");
                }
                
                String ds4 = rs.getString(6);
                if(ds4 != null)
                {
                ds4=ds4.replaceAll(",", "-");
                }
                
                String ds5 = rs.getString(7);
                if(ds5 != null)
                {
                ds5=ds5.replaceAll(",", "-");
                }
                
                String ds6 = rs.getString(8);
                if(ds6 != null)
                {
                ds6=ds6.replaceAll(",", "-");
                }
                
                String ds7 = rs.getString(9);
                if(ds7 != null)
                {
                ds7=ds7.replaceAll(",", "-");
                }
                
                String ds8 = rs.getString(10);
                if(ds2 != null)
                {
                ds8=ds8.replaceAll(",", "-");
                }
                
                if (ds1 == null) {
                    ds1 = " ";
                }
                if (ds2 == null) {
                    ds2 = " ";
                }
                if (ds3 == null) {
                    ds3 = " ";
                }
                if (ds4 == null) {
                    ds4 = " ";
                }
                if (ds5 == null) {
                    ds5 = " ";
                }
                if (ds6 == null) {
                    ds6 = " ";
                }
                if (ds7 == null) {
                    ds7 = " ";
                }
                if (ds8 == null) {
                    ds8 = " ";
                }
                data.add(dhno + "," + dname + "," + ds1 + "," + ds2 + "," + ds3 + "," + ds4 + "," + ds5 + "," + ds6 + "," + ds7 + "," + ds8);
            }
            // System.out.println(data);
            JOptionPane.showMessageDialog(null, "Done writing", "infromation", JOptionPane.INFORMATION_MESSAGE);
            Iterator i = data.listIterator();
            FileOutputStream fis = new FileOutputStream("csebacklogs.csv");
            try (PrintWriter pw = new PrintWriter(fis)) {
                pw.append("\n");
                while (i.hasNext()) {
                    pw.append((CharSequence) i.next());
                    pw.append("\n");
                }
                pw.close();
                JOptionPane.showMessageDialog(null, "Done completed", "infromation", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (FileNotFoundException ex) {
             JOptionPane.showMessageDialog(null, "Cannot Open File ", "File in Use", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | SQLException e) {
              JOptionPane.showMessageDialog(null, "Problem With Database", "Infromation", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        ResultSet rs = null;
        Statement smt = null;
        ArrayList data = new ArrayList();
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite3\\bms");
            con.setAutoCommit(false);
            System.out.println("Opened database successfully");
            smt = con.createStatement();
            rs = smt.executeQuery("Select * from ece");
           
            String hno = "Hallticket Number";
            String name = "Student Name";
            String s1 = "Semester1";
            String s2 = "Semester2";
            String s3 = "Semester3";
            String s4 = "Semester4";
            String s5 = "Semester5";
            String s6 = "Semester6";
            String s7 = "Semester7";
            String s8 = "Semester8";
            data.add("                   Priyadarshini Engineering College Khammam EEE Backlogs Details  ");
            data.add(hno + "," + name + "," + s1 + "," + s2 + "," + s3 + "," + s4 + "," + s5 + "," + s6 + "," + s7 + "," + s8);
            while (rs.next()) {
               String dhno = rs.getString(1);
                String dname = rs.getString(2);
                String ds1 = rs.getString(3);
                ds1=ds1.replaceAll(",","-");
                
                String ds2 = rs.getString(4);
                if(ds2 != null)
                {
                ds2=ds2.replaceAll(",", "-");
                }
                
                String ds3 = rs.getString(5);
                if(ds3 != null)
                {
                ds3=ds3.replaceAll(",", "-");
                }
                
                String ds4 = rs.getString(6);
                if(ds4 != null)
                {
                ds4=ds4.replaceAll(",", "-");
                }
                
                String ds5 = rs.getString(7);
                if(ds5 != null)
                {
                ds5=ds5.replaceAll(",", "-");
                }
                
                String ds6 = rs.getString(8);
                if(ds6 != null)
                {
                ds6=ds6.replaceAll(",", "-");
                }
                
                String ds7 = rs.getString(9);
                if(ds7 != null)
                {
                ds7=ds7.replaceAll(",", "-");
                }
                
                String ds8 = rs.getString(10);
                if(ds2 != null)
                {
                ds8=ds8.replaceAll(",", "-");
                }
                
                if (ds1 == null) {
                    ds1 = " ";
                }
                if (ds2 == null) {
                    ds2 = " ";
                }
                if (ds3 == null) {
                    ds3 = " ";
                }
                if (ds4 == null) {
                    ds4 = " ";
                }
                if (ds5 == null) {
                    ds5 = " ";
                }
                if (ds6 == null) {
                    ds6 = " ";
                }
                if (ds7 == null) {
                    ds7 = " ";
                }
                if (ds8 == null) {
                    ds8 = " ";
                }
                data.add(dhno + "," + dname + "," + ds1 + "," + ds2 + "," + ds3 + "," + ds4 + "," + ds5 + "," + ds6 + "," + ds7 + "," + ds8);
            }
            // System.out.println(data);
            JOptionPane.showMessageDialog(null, "Done writing", "infromation", JOptionPane.INFORMATION_MESSAGE);
            Iterator i = data.listIterator();
            FileOutputStream fis = new FileOutputStream("ecebacklogs.csv");
            try (PrintWriter pw = new PrintWriter(fis)) {
                pw.append("\n");
                while (i.hasNext()) {
                    pw.append((CharSequence) i.next());
                    pw.append("\n");
                }
                pw.close();
                JOptionPane.showMessageDialog(null, "Done completed", "infromation", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (FileNotFoundException ex) {
              JOptionPane.showMessageDialog(null, "Cannot Open File ", "File in Use", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException | SQLException e) {
             JOptionPane.showMessageDialog(null, "Problem With Database", "Infromation", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        main m = new main();
        m.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
