package bms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sandeep
 */
public class ece extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public ece() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jInternalFrame1.setTitle("ECE");
        jInternalFrame1.setVisible(true);

        jLabel1.setText("Hallticket number");

        jLabel2.setText("Name");

        jLabel3.setText("Backlogs");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Backlogs");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Save Backlogs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Delete Backlogs");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6", "Semester 7", "Semester 8", "Optional"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String hallticket = jTextField1.getText();
        String studentname = jTextField2.getText();
        jTable1.editCellAt(0, 0);
        String sem1 = (String) jTable1.getModel().getValueAt(0, 0);
        jTable1.editCellAt(0, 1);
        String sem2 = (String) jTable1.getModel().getValueAt(0, 1);
        jTable1.editCellAt(0, 2);
        String sem3 = (String) jTable1.getModel().getValueAt(0, 2);
        jTable1.editCellAt(0, 3);
        String sem4 = (String) jTable1.getModel().getValueAt(0, 3);
        jTable1.editCellAt(0, 4);
        String sem5 = (String) jTable1.getModel().getValueAt(0, 4);
        jTable1.editCellAt(0, 5);
        String sem6 = (String) jTable1.getModel().getValueAt(0, 5);
        jTable1.editCellAt(0, 6);
        String sem7 = (String) jTable1.getModel().getValueAt(0, 6);
        jTable1.editCellAt(0, 7);
        String sem8 = (String) jTable1.getModel().getValueAt(0, 7);
        jTable1.editCellAt(0, 8);
        Connection con = null;
        PreparedStatement ps = null;

        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite3\\bms");
            con.setAutoCommit(false);
            System.out.println("Opened database successfully");
            String s = "INSERT INTO ece(hno,name,s1,s2,s3,s4,s5,s6,s7,s8) VALUES(?,?,?,?,?,?,?,?,?,?)";
            ps = con.prepareStatement(s);
            ps.setString(1, hallticket);
            ps.setString(2, studentname);
            ps.setString(3, sem1);
            ps.setString(4, sem2);
            ps.setString(5, sem3);
            ps.setString(6, sem4);
            ps.setString(7, sem5);
            ps.setString(8, sem6);
            ps.setString(9, sem7);
            ps.setString(10, sem8);
            int k = ps.executeUpdate();
            if (k != 0) {
                JOptionPane.showMessageDialog(null, "Saved Data of " + studentname + "");
            } else {
                JOptionPane.showMessageDialog(null, "Not saved Data of" + studentname + "");
            }
            ps.close();
            con.commit();
            con.close();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Already Exit Data Your Trying To Save", "Pls Use Update Button", JOptionPane.INFORMATION_MESSAGE);
             JOptionPane.showMessageDialog(null, "Problem With Database", "Infromation", JOptionPane.INFORMATION_MESSAGE);
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }
        System.out.println("Records created successfully");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite3\\bms");
            con.setAutoCommit(false);
            System.out.println("Opened database successfully");
            String s = "select * from ece where hno='" + jTextField1.getText() + "'";
            ps = con.prepareStatement(s);
            rs = ps.executeQuery();
            if (rs.next()) {
                jTextField2.setText(rs.getString("name"));
                String sem1 = rs.getString("s1");
                if (jTable1.contains(0, 1)) {
                    if (sem1 == null ? ("null") == null : sem1.equals("null")) {
                        sem1 = " ";
                    }
                }
                jTable1.setValueAt(sem1, 0, 0);
                
                   String sem2 = rs.getString("s2");
                   if (jTable1.contains(0, 1)) {
                    if (sem2 == null ? ("null") == null : sem2.equals("null")) {
                        sem2 = " ";
                    }
                }
                jTable1.setValueAt(sem2, 0, 1);

                 String sem3 = rs.getString("s3");
                if (jTable1.contains(0, 2)) {
                    if (sem2 == null ? ("null") == null : sem3.equals("null")) {
                        sem3 = " ";
                    }
                }
                jTable1.setValueAt(sem3, 0, 1);

               String sem4 = rs.getString("s4");
                if (jTable1.contains(0, 3)) {
                    if (sem4 == null ? ("null") == null : sem4.equals("null")) {
                        sem4 = " ";
                    }
                }
                jTable1.setValueAt(sem4, 0, 3);
                String sem5 = rs.getString("s5");
                if (jTable1.contains(0, 4)) {
                    if (sem5 == null ? ("null") == null : sem5.equals("null")) {
                        sem5 = " ";
                    }
                }
                jTable1.setValueAt(sem5, 0, 4);
                
                String sem6 = rs.getString("s6");
                if (jTable1.contains(0, 5)) {
                    if (sem6 == null ? ("null") == null : sem6.equals("null")) {
                        sem6 = " ";
                    }
                }
                jTable1.setValueAt(sem6, 0, 5);
                String sem7 = rs.getString("s7");

                if (jTable1.contains(0, 6)) {
                    if (sem7 == null ? ("null") == null : sem7.equals("null")) {
                        sem7 = " ";
                    }
                }
                jTable1.setValueAt(sem7, 0, 6);
                             
                String sem8 = rs.getString("s8");
                if (jTable1.contains(0, 7)) {
                    if (sem8 == null ? ("null") == null : sem8.equals("null")) {
                        sem8 = " ";
                    }
                }
                jTable1.setValueAt(sem8, 0, 7);
                
                jTable1.setValueAt(" ", 0, 8);
                jTable1.setValueAt(" ", 0, 8);
              
            }
             else {
                JOptionPane.showMessageDialog(null, "Record Not Found  " + "");
            }
            ps.close();
            con.commit();
            con.close();
        } catch (ClassNotFoundException | SQLException e) {
             JOptionPane.showMessageDialog(null, "Problem With Database", "Infromation", JOptionPane.INFORMATION_MESSAGE);
             System.err.println(e.getClass().getName() + ": " + e.getMessage());
            //System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String hallticket = jTextField1.getText();
        String studentname = jTextField2.getText();
        jTable1.editCellAt(0, 0);
        String sem1 = (String) jTable1.getModel().getValueAt(0, 0);
        jTable1.editCellAt(0, 1);
        String sem2 = (String) jTable1.getModel().getValueAt(0, 1);
        jTable1.editCellAt(0, 2);
        String sem3 = (String) jTable1.getModel().getValueAt(0, 2);
        jTable1.editCellAt(0, 3);
        String sem4 = (String) jTable1.getModel().getValueAt(0, 3);
        jTable1.editCellAt(0, 4);
        String sem5 = (String) jTable1.getModel().getValueAt(0, 4);
        jTable1.editCellAt(0, 5);
        String sem6 = (String) jTable1.getModel().getValueAt(0, 5);
        jTable1.editCellAt(0, 6);
        String sem7 = (String) jTable1.getModel().getValueAt(0, 6);
        jTable1.editCellAt(0, 7);
        String sem8 = (String) jTable1.getModel().getValueAt(0, 7);
        jTable1.editCellAt(0, 8);
        Connection con = null;
        Statement smt = null;
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite3\\bms");
            con.setAutoCommit(false);
            System.out.println("Opened database successfully");
            smt = con.createStatement();
            String s = "update ece set hno='" + hallticket + "',name='" + studentname + "',s1='" + sem1 + "',s2='" + sem2 + "',s3='" + sem3 + "',s4='" + sem4 + "' ,s5='" + sem5 + "' ,s6='" + sem6 + "',s7='" + sem7 + "',s8='" + sem8 + "'where hno='" + hallticket + "'";
            int k = smt.executeUpdate(s);
            if (k != 0) {
                JOptionPane.showMessageDialog(null, "updated Data of " + studentname + "");
            } else {
                JOptionPane.showMessageDialog(null, "Not updated Data of" + studentname + "");
            }
            smt.close();
            con.commit();
            con.close();
        } catch (ClassNotFoundException | SQLException e) {
             JOptionPane.showMessageDialog(null, "Problem With Database", "Infromation", JOptionPane.INFORMATION_MESSAGE);
             System.err.println(e.getClass().getName() + ": " + e.getMessage());
            //System.exit(0);
        }
        System.out.println("Records created successfully");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        main m = new main();
        m.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jTable1.contains(0, 0) && jTable1.contains(0, 1) && jTable1.contains(0, 2) && jTable1.contains(0, 3) && jTable1.contains(0, 4) && jTable1.contains(0, 5)
                && jTable1.contains(0, 6) && jTable1.contains(0, 7) && jTable1.contains(0, 8));
        {
            JOptionPane.showMessageDialog(null, "some backlog data is there", "what to delete", JOptionPane.INFORMATION_MESSAGE);
        }
        String hallticket = jTextField1.getText();
        Connection con = null;
        Statement smt = null;
        try {
            Class.forName("org.sqlite.JDBC");
            con = DriverManager.getConnection("jdbc:sqlite:C:\\sqlite3\\bms");
            con.setAutoCommit(false);
            System.out.println("Opened database successfully");
            smt = con.createStatement();
            String s = "delete from ece where hno='" + hallticket + "'";
            int k = smt.executeUpdate(s);
            if (k != 0) {
                JOptionPane.showMessageDialog(null, "Deleted Data of " + hallticket + "");
            } else {
                JOptionPane.showMessageDialog(null, "Problem to  Delete Data of" + hallticket + "");
            }
            smt.close();
            con.commit();
            con.close();
        } catch (ClassNotFoundException | SQLException e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            System.exit(0);
        }
        System.out.println("Records created successfully");

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ece.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ece().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
